# Generated by Django 4.2 on 2023-04-05 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Сharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField()),
                ('mana', models.IntegerField()),
                ('weapon', models.CharField(choices=[('gun', 'Gun'), ('axe', 'Axe'), ('sword', 'Sword'), ('magic', 'Magic')], max_length=100)),
                ('who', models.CharField(choices=[('mage', 'Mage'), ('war', 'War'), ('rogue', 'Roque'), ('archer', 'Archer')], max_length=40)),
                ('hp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('lor', models.TextField()),
                ('fraction', models.CharField(choices=[('tg', 'Targon'), ('io', 'Ionia'), ('nx', 'Noxus'), ('dm', 'Demacia'), ('pz', 'Piltover & Zaun'), ('fj', 'Freljord'), ('si', 'Shadow Isles'), ('bw', 'Bilgewater')], max_length=100)),
                ('name', models.CharField(default='Unknow', max_length=30)),
                ('character', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lor.сharacteristics')),
            ],
        ),
    ]
