# Generated by Django 4.2 on 2023-04-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pers',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
