# Generated by Django 4.2 on 2023-04-10 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lor', '0004_alter_pers_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pers',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lor.сharacteristics'),
        ),
        migrations.AlterField(
            model_name='pers',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='avatars/'),
        ),
    ]
